appkey: com.qiafengqishi.nuoya

#服务启动端口号
server:
  port: 8080


spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/web-flash?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  resources:
    static-locations: classpath:/static/

  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
#    suffix: .html
    template-loader-path: classpath:/templates
    settings.template_update_delay: 0
    settings.default_encoding: UTF-8
    settings.classic_compatible: true
    order: 2
    settings.number_format: 0.##

service:
  test:
    a: 123
    b: 1234